#!/bin/bash
cd latex
cp -rf ../template/* .
cp -rf ../contents/img .
ls -al img
multimarkdown -t latex meta.txt ../contents/0-preface*.markdown -o preface.tex
multimarkdown -t latex meta.txt ../contents/1-chapter*.markdown -o chapters.tex
multimarkdown -t latex meta.txt ../contents/2-appendix*.markdown -o appendix.tex
cp template.tex sdcamp.tex
xelatex sdcamp.tex
xelatex sdcamp.tex
xelatex sdcamp.tex
cp sdcamp.pdf ..
echo
echo
echo "Done!"
